project:
  type: website
  output-dir: docs

website:
  title: "Clara"
  
  navbar:
    left:
      - text: 블로그
        href: index.qmd
      - text: "수학I"
        href: posts/math_I/index.qmd
      - text: "Python"
        href: posts/python/Python.qmd
    right:
      - posts/about.qmd
      - icon: github
        href: https://github.com/
    search: true
    
  sidebar:
    - title: "수학I"
      collapse-level: 2
      contents:
        - posts//math_I/index.qmd
        - section: "지수함수와 로그함수"
          contents:
          - posts/math_I/exponent/curriculum.qmd     
          - posts/math_I/exponent/exponent.qmd
          - posts/math_I/exponent/concept_exponent.qmd             
          - posts/math_I/exponent/day1.qmd   
          - posts/math_I/exponent/day2.qmd 
          - posts/math_I/exponent/exercise3.qmd           
        - section: "사칙연산"
          contents:
          - posts/math_I/sequence/sequence.qmd          
    - title: "Python"
      collapse-level: 2
      contents:
        - posts/python/Python.qmd

format:
  html:
    theme: cosmo
    relative-resources: true
    css: styles/tooltip.css
    csl: styles/nuclear-medicine-and-molecular-imaging.csl
    toc: true
    toc-depth: 4
    include-after-body:
      - text: |
          <script src="/scripts/tooltip.js"></script>
    
    comments:
      utterances:
        repo: RadiationSafetyNM/website