project:
  type: website
  output-dir: ./docs

website:
  title: "Clara"
  navbar:
    # logo: RPythonStudy_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: Python.qmd
        text: Python


format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true

editor: visual

