---
title: "교육과정"
description: "수학I  -  2015년 개정"
date: "2024-12-21"
modified-date: "2024-12-21"
categories: [수학I, 교육과정, 2015년 개정]
toc-depth: 4
---

### 1. 성격

수학과는 수학의 개념, 원리, 법칙을 이해하고 기능을 습득하여 주변의 여러 가지 현상을 수학적으로 관찰하고 해석하며 논리적으로 사고하고 합리적으로 문제를 해결하는 능력과 태도를 기르는 교과이다.
수학은 오랜 역사를 통해 인류 문명 발전의 원동력이 되어 왔으며, 세계화･정보화가 가속화되는 미래 사회의 구성원에게 필수적인 역량을 제공한다.
수학 학습을 통해 학생들은 수학의 규칙성과 구조의 아름다움을 음미할 수 있고, 수학의 지식과 기능을 활용하여 수학 문제뿐만 아니라 실생활과 다른 교과의 문제를 창의적으로 해결할 수 있으며, 나아가 세계 공동체의 시민으로서 갖추어야 할 합리적 의사 결정 능력과 민주적 소통 능력을 함양할 수 있다.

일반 선택 과목인 <수학Ⅰ>은 공통 과목인 <수학>을 학습한 후, 더 높은 수준의 수학을 학습하기를 원하는 학생들이 선택할 수 있는 과목이다.
<수학Ⅰ>의 내용은 ʻ지수함수와 로그함수ʼ, ʻ삼각함수ʼ, ʻ수열ʼ의 3개 핵심 개념 영역으로 구성된다.
ʻ지수함수와 로그함수ʼ 영역에서는 지수와 로그, 지수함수와 로그함수를, ʻ삼각함수ʼ 영역에서는 일반각과 호도법, 삼각함수의 뜻과 그래프, 사인법칙과 코사인법칙을, ʻ수열ʼ 영역에서는 등차수열과 등비수열, 수열의 합, 수학적 귀납법을 다룬다.

<수학Ⅰ>에서 학습한 수학의 지식과 기능은 자신의 진로와 적성을 고려하여 선택할 수 있는 수학 일반 선택 과목과 진로 선택 과목, 수학 전문 교과 과목을 학습하기 위한 토대가 되고, 자연과학, 공학, 의학뿐만 아니라 경제･경영학을 포함한 사회과학, 인문학, 예술 및 체육 분야를 학습하는 데 기초가 되며, 나아가 창의적 역량을 갖춘 융합 인재로 성장할 수 있는 기반을 제공한다.
이를 위해 학생들은 <수학Ⅰ>의 지식을 이해하고 기능을 습득하는 것과 더불어 문제 해결, 추론, 창의･융합, 의사소통, 정보 처리, 태도 및 실천의 6가지 수학 교과 역량을 길러야 한다.

교과 역량으로서의 문제 해결은 해결 방법을 알고 있지 않은 문제 상황에서 수학의 지식과 기능을 활용하여 해결 전략을 탐색하고 최적의 해결 방안을 선택하여 주어진 문제를 해결하는 능력이고, 추론은 수학적 사실을 추측하고 논리적으로 분석하고 정당화하며 그 과정을 반성하는 능력이다.
창의･융합은 수학의 지식과 기능을 토대로 새롭고 의미 있는 아이디어를 다양하고 풍부하게 산출하고 정교화하며, 여러 수학적 지식, 기능, 경험을 연결하거나 타 교과나 실생활의 지식, 기능, 경험을 수학과 연결･융합하여 새로운 지식, 기능, 경험을 생성하고 문제를 해결하는 능력이다.
의사소통은 수학 지식이나 아이디어, 수학적 활동의 결과, 문제 해결 과정, 신념과 태도 등을 말이나 글, 그림, 기호로 표현하고 다른 사람의 아이디어를 이해하는 능력이고, 정보 처리는 다양한 자료와 정보를 수집, 정리, 분석, 활용하고 적절한 공학적 도구나 교구를 선택, 이용하여 자료와 정보를 효과적으로 처리하는 능력이다.
끝으로, 태도 및 실천은 수학의 가치를 인식하고 자주적 수학 학습 태도와 민주 시민 의식을 갖추어 실천하는 능력이다.

수학 교과 역량 함양을 통해 학생들은 복잡하고 전문화되어 가는 미래 사회에서 사회 구성원의 역할을 성공적으로 수행할 수 있고, 개인의 잠재력과 재능을 발현할 수 있으며, 수학의 필요성과 유용성을 이해하고, 수학 학습의 즐거움을 느끼며, 수학에 대한 흥미와 자신감을 기를 수 있다.

### 2. 목표

수학의 개념, 원리, 법칙을 이해하고 기능을 습득하며 수학적으로 추론하고 의사소통하는 능력을 길러, 생활 주변과 사회 및 자연 현상을 수학적으로 이해하고 문제를 합리적이고 창의적으로 해결하며, 수학 학습자로서 바람직한 태도와 실천 능력을 기른다.

가.
사회 및 자연 현상을 수학적으로 관찰, 분석, 조직, 표현하는 경험을 통하여 지수함수와 로그함수, 삼각함수, 수열에 관련된 개념, 원리, 법칙과 이들 사이의 관계를 이해하고 수학의 기능을 습득한다.

나.
수학적으로 추론하고 의사소통하며, 창의･융합적 사고와 정보 처리 능력을 바탕으로 사회 및 자연 현상을 수학적으로 이해하고 문제를 합리적이고 창의적으로 해결한다.

다.
수학에 대한 흥미와 자신감을 갖고 수학의 역할과 가치를 이해하며 수학 학습자로서 바람직한 태도와 실천 능력을 기른다.

### 지수함수와 로그함수

지수함수는 빠르게 증가하거나 감소하는 수량이나 현상을 다루는 데 유용한 함수이고, 로그함수는 지수함수의 역함수이다.
지수함수와 로그함수는 자연 현상이나 사회 현상을 설명하고 분석하기 위한 수학적 모델이다.

#### 1. 지수와 로그

-   \[12수학Ⅰ01-01\]거듭제곱과 거듭제곱근의 뜻을 알고, 그 성질을 이해한다.
-   \[12수학Ⅰ01-02\]지수가 유리수, 실수까지 확장될 수 있음을 이해한다.
-   \[12수학Ⅰ01-03\]지수법칙을 이해하고, 이를 이용하여 식을 간단히 나타낼 수 있다.
-   \[12수학Ⅰ01-04\]로그의 뜻을 알고, 그 성질을 이해한다.
-   \[12수학Ⅰ01-05\]상용로그를 이해하고, 이를 활용할 수 있다.

#### 2. 지수함수와 로그함수

-   \[12수학Ⅰ01-06\]지수함수와 로그함수의 뜻을 안다.
-   \[12수학Ⅰ01-07\]지수함수와 로그함수의 그래프를 그릴 수 있고, 그 성질을 이해한다.
-   \[12수학Ⅰ01-08\]지수함수와 로그함수를 활용하여 문제를 해결할 수 있다.

### 삼각함수

삼각함수는 삼각비를 일반화시킨 개념으로, 자연 현상이나 사회 현상 가운데 나타나는 주기적인 현상을 수학적으로 표현하여 설명하고 분석할 수 있는 유용한 주기함수이다.
사인법칙과 코사인법칙을 포함한 삼각함수의 성질은 삼각형으로 나타낼 수 있는 대상의 길이, 넓이, 각도 등의 측정과 관련된 다양한 문제의 해결에 활용된다.

#### 1. 삼각함수

-   \[12수학Ⅰ02-01\]일반각과 호도법의 뜻을 안다.
-   \[12수학Ⅰ02-02\]삼각함수의 뜻을 알고, 사인함수, 코사인함수, 탄젠트함수의 그래프를 그릴 수 있다.
-   \[12수학Ⅰ02-03\]사인법칙과 코사인법칙을 이해하고, 이를 활용할 수 있다.

### 수열

수열은 규칙적으로 나열된 수로 나타낼 수 있는 현상을 탐구하는 데 유용한 함수이다.
수열을 통해 자연 현상이나 사회 현상에 내재되어 있는 다양한 규칙성을 찾아 일반화된 식으로 표현하고 수학적으로 정당화함으로써 수학의 유용성과 가치를 경험하고 귀납적 추론 능력과 연역적 추론 능력을 기를 수 있다.

#### 1. 등차수열과 등비수열

-   \[12수학Ⅰ03-01\]수열의 뜻을 안다.
-   \[12수학Ⅰ03-02\]등차수열의 뜻을 알고, 일반항, 첫째항부터 제$n$항까지의 합을 구할 수 있다.
-   \[12수학Ⅰ03-03\]등비수열의 뜻을 알고, 일반항, 첫째항부터 제$n$항까지의 합을 구할 수 있다.

#### 2. 수열의 합

-   \[12수학Ⅰ03-04\]$\Sigma$의 뜻을 알고, 그 성질을 이해하고, 이를 활용할 수 있다.
-   \[12수학Ⅰ03-05\]여러 가지 수열의 첫째항부터 제$n$항까지의 합을 구할 수 있다.

#### 3. 수학적 귀납법

-   \[12수학Ⅰ03-06\]수열의 귀납적 정의를 이해한다.
-   \[12수학Ⅰ03-07\]수학적 귀납법의 원리를 이해한다.
-   \[12수학Ⅰ03-08\]수학적 귀납법을 이용하여 명제를 증명할 수 있다.
