---
title: "교육과정"
description: "중3수학  -  2015년 개정"
date: "2024-12-28"
date-modified: "2024-12-28"
categories: [중3수학, 교육과정, 2015년 개정]
toc-depth: 4
---

## 중3과정

### 1. 수와 연산

#### 제곱근과 실수
- [9수01-07]제곱근의 뜻을 알고, 그 성질을 이해한다.
- [9수01-08]무리수의 개념을 이해한다. 
- [9수01-09]실수의 대소 관계를 판단할 수 있다. 
- [9수01-10]근호를 포함한 식의 사칙계산을 할 수 있다.

### 2. 문자와 식

#### 다항식의 곱셈과 인수분해
[9수02-12]다항식의 곱셈과 인수분해를 할 수 있다.

#### 이차방정식
[9수02-13]이차방정식을 풀 수 있고, 이를 활용하여 문제를 해결할 수 있다.

### 3. 함수

#### 이차함수와 그래프
- [9수03-09]이차함수의 의미를 이해하고, 그 그래프를 그릴 수 있다.
- [9수03-10]이차함수의 그래프의 성질을 이해한다.

### 4. 기하

#### 삼각비
- [9수04-17]삼각비의 뜻을 알고, 간단한 삼각비의 값을 구할 수 있다. 
- [9수04-18]삼각비를 활용하여 여러 가지 문제를 해결할 수 있다.

#### 원의 성질
- [9수04-19]원의 현에 관한 성질과 접선에 관한 성질을 이해한다.
- [9수04-20]원주각의 성질을 이해한다. 

### 5. 확률과 통계

#### 대푯값과 산포도
- [9수05-06]중앙값, 최빈값, 평균의 의미를 이해하고, 이를 구할 수 있다.
- [9수05-07]분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.

#### 상관관계
- [9수05-08]자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.


## 중학교 전체과정

### 1. 수와 연산
수는 방정식의 해의 존재를 보장하기 위해 정수, 유리수, 실수 등으로 확장되고, 각각의 수체계에서 사칙계산이 정의되고 연산의 성질이 일관되게 성립한다. 수는 수학에서 다루는 가장 기본적인 개념으로, 실생활뿐 아니라 타 교과나 수학의 다른 영역을 학습하는 데 필수적이다. 또한 수의 연산은 수학 학습에서 습득해야 할 가장 기본적인 기능 중 하나로, 이후 학습을 위한 기초가 된다.

#### 소인수분해 
- [9수01-01]소인수분해의 뜻을 알고, 자연수를 소인수분해할 수 있다. 
- [9수01-02]최대공약수와 최소공배수의 성질을 이해하고, 이를 구할 수 있다.

#### 정수와 유리수
- [9수01-03]양수와 음수, 정수와 유리수의 개념을 이해한다.
- [9수01-04]정수와 유리수의 대소 관계를 판단할 수 있다.
- [9수01-05]정수와 유리수의 사칙계산의 원리를 이해하고, 그 계산을 할 수 있다.

#### 유리수와 순환소수
- [9수01-06]순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 이해한다.

#### 제곱근과 실수
- [9수01-07]제곱근의 뜻을 알고, 그 성질을 이해한다.
- [9수01-08]무리수의 개념을 이해한다. 
- [9수01-09]실수의 대소 관계를 판단할 수 있다. 
- [9수01-10]근호를 포함한 식의 사칙계산을 할 수 있다.


### 2. 문자와 식
문자는 수량 관계를 명확하고 간결하게 표현하는 수학적 언어이다. 문자를 통해 수량 사이의 관계를 일반화함으로써 산술에서 대수로 이행하며, 수에 대한 사칙연산과 소인수분해는 다항식으로 확장되어 적용된다. 또한 방정식과 부등식은 양 사이의 관계를 나타내며, 적절한 절차를 따라 이를 만족시키는 해를 구할 수 있다. 문자는 수학적 의사소통을 원활히 할 수 있도록 도와주고, 문자를 이용한 방정식과 부등식은 여러 가지 문제를 해결하는 중요한 도구가 된다.

#### 문자의 사용과 식의 계산
- [9수02-01]다양한 상황을 문자를 사용한 식으로 나타낼 수 있다. 
- [9수02-02]식의 값을 구할 수 있다.
- [9수02-03]일차식의 덧셈과 뺄셈의 원리를 이해하고, 그 계산을 할 수 있다.

#### 일차방정식
[9수02-04]방정식과 그 해의 의미를 알고, 등식의 성질을 이해한다. 
[9수02-05]일차방정식을 풀 수 있고, 이를 활용하여 문제를 해결할 수 있다.

#### 식의 계산
[9수02-06]지수법칙을 이해한다.
[9수02-07]다항식의 덧셈과 뺄셈의 원리를 이해하고, 그 계산을 할 수 있다.
[9수02-08]‘(단항식)×(다항식)’, ‘(다항식)÷(단항식)’과 같은 곱셈과 나눗셈의 원리를 이해하고, 그 계산을 할 수 있다.

#### 일차부등식과 연립일차방정식
[9수02-09]부등식과 그 해의 의미를 알고, 부등식의 성질을 이해한다.
[9수02-10]일차부등식을 풀 수 있고, 이를 활용하여 문제를 해결할 수 있다. 
[9수02-11]미지수가 2개인 연립일차방정식을 풀 수 있고, 이를 활용하여 문제를 해결할 수 있다.

#### 다항식의 곱셈과 인수분해
[9수02-12]다항식의 곱셈과 인수분해를 할 수 있다.

#### 이차방정식
[9수02-13]이차방정식을 풀 수 있고, 이를 활용하여 문제를 해결할 수 있다.

### 3. 함수
변화하는 양 사이의 관계를 나타내는 함수는 대응과 종속의 의미를 포함하며, 그래프는 함수를 시각적으로 표현하는 도구이다. 여러 가지 현상에서 관찰할 수 있는 규칙 중에는 한 값이 변하면 다른 값도 일정한 규칙에 따라 변하는 것들이 많이 있다. 함수는 다양한 변화 현상 속의 수학적 관계를 이해하고 표현함으로써 여러 가지 문제를 해결하는 데 도움이 된다. 

#### 좌표평면과 그래프 
- [9수03-01]순서쌍과 좌표를 이해한다.
- [9수03-02]다양한 상황을 그래프로 나타내고, 주어진 그래프를 해석할 수 있다.
- [9수03-03]정비례, 반비례 관계를 이해하고, 그 관계를 표, 식, 그래프로 나타낼 수 있다. 

#### 일차함수와 그래프
- [9수03-04]함수의 개념을 이해한다. 
- [9수03-05]일차함수의 의미를 이해하고, 그 그래프를 그릴 수 있다.
- [9수03-06]일차함수의 그래프의 성질을 이해하고, 이를 활용하여 문제를 해결할 수 있다.

#### 일차함수와 일차방정식의 관계
- [9수03-07]일차함수와 미지수가 2개인 일차방정식의 관계를 이해한다.
- [9수03-08]두 일차함수의 그래프와 연립일차방정식의 관계를 이해한다.

#### 이차함수와 그래프
- [9수03-09]이차함수의 의미를 이해하고, 그 그래프를 그릴 수 있다.
- [9수03-10]이차함수의 그래프의 성질을 이해한다.


### 4. 기하
주변의 형태는 여러 가지 평면도형이나 입체도형으로 범주화 되고, 각각의 평면도형이나 입체도형은 고유한 성질을 갖는다. 평면도형이나 입체도형의 성질에 대한 이해는 다양한 분야의 실생활 문제를 해결하는 데 기초가 되며, 수학의 다른 영역의 개념과 밀접하게 관련되어 있다. 도형의 성질을 정당화하는 과정에서 요구되는 연역적 추론은 수학적 소양을 기르는 데 도움이 된다. 

#### 기본 도형 
- [9수04-01]점, 선, 면, 각을 이해하고, 점, 직선, 평면의 위치 관계를 설명할 수 있다. 
- [9수04-02]평행선에서 동위각과 엇각의 성질을 이해한다.

#### 작도와 합동
- [9수04-03]삼각형을 작도할 수 있다.
- [9수04-04]삼각형의 합동 조건을 이해하고, 이를 이용하여 두 삼각형이 합동인지 판별할 수 있다.

#### 평면도형의 성질
- [9수04-05]다각형의 성질을 이해한다.
- [9수04-06]부채꼴의 중심각과 호의 관계를 이해하고, 이를 이용하여 부채꼴의 넓이와 호의 길이를 구할 수 있다.

#### 입체도형의 성질
- [9수04-07]다면체의 성질을 이해한다. 
- [9수04-08]회전체의 성질을 이해한다.
- [9수04-09]입체도형의 겉넓이와 부피를 구할 수 있다. 

#### 삼각형과 사각형의 성질
- [9수04-10]이등변삼각형의 성질을 이해하고 설명할 수 있다.
- [9수04-11]삼각형의 외심과 내심의 성질을 이해하고 설명할 수 있다.
- [9수04-12]사각형의 성질을 이해하고 설명할 수 있다.

#### 도형의 닮음
- [9수04-13]도형의 닮음의 의미와 닮은 도형의 성질을 이해한다.
- [9수04-14]삼각형의 닮음 조건을 이해하고, 이를 이용하여 두 삼각형이 닮음인지 판별할 수 있다.
- [9수04-15]평행선 사이의 선분의 길이의 비를 구할 수 있다. 

#### 피타고라스 정리
- [9수04-16]피타고라스 정리를 이해하고 설명할 수 있다. 

#### 삼각비
- [9수04-17]삼각비의 뜻을 알고, 간단한 삼각비의 값을 구할 수 있다. 
- [9수04-18]삼각비를 활용하여 여러 가지 문제를 해결할 수 있다.

#### 원의 성질
- [9수04-19]원의 현에 관한 성질과 접선에 관한 성질을 이해한다.
- [9수04-20]원주각의 성질을 이해한다. 

### 5. 확률과 통계
사건이 일어날 가능성을 수치화한 확률, 그리고 자료를 수집, 정리, 해석하는 통계는 현대 정보화 사회의 불확실성을 이해하는 중요한 도구이다. 다양한 자료를 수집, 정리, 해석하고, 확률을 이해함으로써, 미래를 예측하고 합리적인 의사 결정을 하는 민주 시민으로서의 기본 소양을 기를 수 있다.

#### 자료의 정리와 해석
- [9수05-01]자료를 줄기와 잎 그림, 도수분포표, 히스토그램, 도수분포다각형으로 나타내고 해석할 수 있다.
- [9수05-02]상대도수를 구하며, 이를 그래프로 나타내고, 상대도수의 분포를 이해한다.
- [9수05-03]공학적 도구를 이용하여 실생활과 관련된 자료를 수집하고 표나 그래프로 정리하고 해석할 수 있다.

#### 확률과 그 기본 성질
- [9수05-04]경우의 수를 구할 수 있다.
- [9수05-05]확률의 개념과 그 기본 성질을 이해하고, 확률을 구할 수 있다.

#### 대푯값과 산포도
- [9수05-06]중앙값, 최빈값, 평균의 의미를 이해하고, 이를 구할 수 있다.
- [9수05-07]분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.

#### 상관관계
- [9수05-08]자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.

